"""modificando models de suministro

Revision ID: 1ee6c8ecbc06
Revises: 08b040e13830
Create Date: 2026-03-11 23:37:37.514317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ee6c8ecbc06'
down_revision: Union[str, Sequence[str], None] = '08b040e13830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suministro', sa.Column('precio_unitario', sa.Float(), nullable=True))
    op.add_column('suministro', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('suministro', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suministro', 'deleted_at')
    op.drop_column('suministro', 'created_at')
    op.drop_column('suministro', 'precio_unitario')
    # ### end Alembic commands ###
