"""cambios fechas

Revision ID: 470ea6789fe0
Revises: e7c8ff7e09e5
Create Date: 2026-03-03 19:35:18.757619

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "470ea6789fe0"
down_revision: Union[str, Sequence[str], None] = "e7c8ff7e09e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column(
        "productos",
        "created_at",
        existing_type=sa.DateTime(),
        server_default=sa.func.now(),
    )
    op.alter_column(
        "productos",
        "updated_at",
        existing_type=sa.DateTime(),
        server_default=sa.func.now(),
    )
    op.alter_column(
        "productos",
        "deleted_at",
        existing_type=sa.DateTime(),
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
