"""primera migracion

Revision ID: b69f0721b80f
Revises: 
Create Date: 2026-03-02 02:55:04.244403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b69f0721b80f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operador',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('rol', sa.Enum('admin', 'operador', name='rolenum'), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operador_email'), 'operador', ['email'], unique=True)
    op.create_index(op.f('ix_operador_id'), 'operador', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operador_id'), table_name='operador')
    op.drop_index(op.f('ix_operador_email'), table_name='operador')
    op.drop_table('operador')
    # ### end Alembic commands ###
