"""add ventas row in movimientos table

Revision ID: cd9064169c74
Revises: 362dc1298a65
Create Date: 2026-03-15 21:15:11.366886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd9064169c74'
down_revision: Union[str, Sequence[str], None] = '362dc1298a65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movimientos', sa.Column('venta_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'movimientos', 'ventas', ['venta_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movimientos', type_='foreignkey')
    op.drop_column('movimientos', 'venta_id')
    # ### end Alembic commands ###
