"""movimientos

Revision ID: e6b291c4698c
Revises: 68f913d6c045
Create Date: 2026-03-02 06:39:53.489293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6b291c4698c'
down_revision: Union[str, Sequence[str], None] = '68f913d6c045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimientos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('tipo', sa.Enum('venta', 'restock', 'ajuste', name='tipoenum'), nullable=False),
    sa.Column('producto_id', sa.BigInteger(), nullable=False),
    sa.Column('operador_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['operador_id'], ['operador.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_id'), 'movimientos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimientos_id'), table_name='movimientos')
    op.drop_table('movimientos')
    # ### end Alembic commands ###
