"""suministro

Revision ID: e7c8ff7e09e5
Revises: e6b291c4698c
Create Date: 2026-03-02 06:56:42.528895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7c8ff7e09e5'
down_revision: Union[str, Sequence[str], None] = 'e6b291c4698c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suministro',
    sa.Column('producto_id', sa.BigInteger(), nullable=False),
    sa.Column('proveedor_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('producto_id', 'proveedor_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suministro')
    # ### end Alembic commands ###
