"""cambios fechas

Revision ID: edfe4e5f63ab
Revises: 470ea6789fe0
Create Date: 2026-03-03 19:45:08.683007

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "edfe4e5f63ab"
down_revision: Union[str, Sequence[str], None] = "470ea6789fe0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column("productos", "created_at", server_default=sa.func.now())
    op.alter_column("productos", "updated_at", server_default=sa.func.now())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
